import { AdminNavItem, AdminNavSection } from './admin-nav.model';

export const ADMIN_NAV_SECTIONS: AdminNavSection[] = [
  {
    id: 'main',
    labelAr: 'الرئيسية',
    labelEn: 'Main',
    items: [
      {
        id: 'overview',
        labelAr: 'نظرة عامة',
        labelEn: 'Overview',
        descriptionAr: 'مؤشرات اليوم وملخص العمليات',
        descriptionEn: 'Daily KPIs and operations summary',
        route: '/admin/overview',
        icon: 'lucideLayoutDashboard',
      },
    ],
  },
  {
    id: 'accounts',
    labelAr: 'الحسابات',
    labelEn: 'Accounts',
    items: [
      {
        id: 'accounts-group',
        labelAr: 'اعتماد الحسابات',
        labelEn: 'Account Approvals',
        icon: 'lucideUsers',
        children: [
          {
            id: 'pending-accounts',
            labelAr: 'طلبات قيد المراجعة',
            labelEn: 'Pending Review',
            descriptionAr: 'مراجعة واعتماد حسابات المطاعم والسائقين',
            descriptionEn: 'Review and approve restaurant and driver accounts',
            route: '/admin/accounts/pending',
            icon: 'lucideUserCheck',
            badge: 12,
          },
          {
            id: 'restaurants',
            labelAr: 'المطاعم',
            labelEn: 'Restaurants',
            descriptionAr: 'إدارة حالة المطاعم والوثائق',
            descriptionEn: 'Manage restaurant status and documents',
            route: '/admin/accounts/restaurants',
            icon: 'lucideStore',
          },
          {
            id: 'drivers',
            labelAr: 'السائقون',
            labelEn: 'Drivers',
            descriptionAr: 'التحقق من السائقين وحالة العمل',
            descriptionEn: 'Driver verification and work status',
            route: '/admin/accounts/drivers',
            icon: 'lucideTruck',
            badge: 4,
          },
        ],
      },
    ],
  },
  {
    id: 'operations',
    labelAr: 'العمليات',
    labelEn: 'Operations',
    items: [
      {
        id: 'operations-group',
        labelAr: 'مركز العمليات',
        labelEn: 'Operations Hub',
        icon: 'lucideClock',
        children: [
          {
            id: 'orders',
            labelAr: 'الطلبات',
            labelEn: 'Orders',
            descriptionAr: 'مركز موحّد للطلبات — فلاتر حسب المرحلة وإجراءات التدخل',
            descriptionEn: 'Unified orders hub — phase filters and intervention actions',
            route: '/admin/operations/orders',
            icon: 'lucideLayoutDashboard',
            badge: 5,
          },
          {
            id: 'delivery',
            labelAr: 'التوصيل',
            labelEn: 'Delivery',
            descriptionAr: 'تتبع مباشر وحالات Hold',
            descriptionEn: 'Live tracking and hold cases',
            route: '/admin/operations/delivery',
            icon: 'lucideMapPinned',
            badge: 4,
          },
          {
            id: 'audit',
            labelAr: 'سجل الاستثناءات',
            labelEn: 'Exception Audit',
            descriptionAr: 'سجل تدقيق للإجراءات داخل نافذة 72h',
            descriptionEn: 'Audit log for in-window admin actions',
            route: '/admin/operations/audit',
            icon: 'lucideShieldAlert',
            badge: 1,
          },
        ],
      },
    ],
  },
  {
    id: 'subscriptions',
    labelAr: 'الاشتراكات والتسعير',
    labelEn: 'Subscriptions & Pricing',
    items: [
      {
        id: 'subscriptions-group',
        labelAr: 'الاشتراكات',
        labelEn: 'Subscriptions',
        icon: 'lucideTags',
        children: [
          {
            id: 'programs',
            labelAr: 'البرامج والباقات',
            labelEn: 'Programs & Bundles',
            descriptionAr: 'إدارة البرامج والباقات والمدد',
            descriptionEn: 'Manage programs, bundles, and durations',
            route: '/admin/subscriptions/programs',
            icon: 'lucideLayers',
          },
          {
            id: 'tiers',
            labelAr: 'تصنيف المطاعم',
            labelEn: 'Restaurant Tiers',
            descriptionAr: 'Basic / Platinum / Elite حسب السعر',
            descriptionEn: 'Basic / Platinum / Elite by price band',
            route: '/admin/subscriptions/tiers',
            icon: 'lucideAward',
          },
          {
            id: 'pricing',
            labelAr: 'التسعير والعمولات',
            labelEn: 'Pricing & Commissions',
            descriptionAr: 'سياسة التسعير وعمولة المنصة',
            descriptionEn: 'Pricing policy and platform commission',
            route: '/admin/subscriptions/pricing',
            icon: 'lucidePercent',
          },
        ],
      },
    ],
  },
  {
    id: 'finance',
    labelAr: 'المالية',
    labelEn: 'Finance',
    items: [
      {
        id: 'finance-group',
        labelAr: 'المحاسبة',
        labelEn: 'Accounting',
        icon: 'lucideWallet',
        children: [
          {
            id: 'cancellations',
            labelAr: 'الإلغاء والاسترداد',
            labelEn: 'Cancellations & Refunds',
            descriptionAr: 'مراجعة طلبات الإلغاء وحساب الاسترداد',
            descriptionEn: 'Review cancellations and refund calculations',
            route: '/admin/finance/cancellations',
            icon: 'lucideUndo2',
            badge: 5,
          },
          {
            id: 'settlements',
            labelAr: 'تسويات المطاعم',
            labelEn: 'Restaurant Settlements',
            descriptionAr: 'تسويات الصناديق المسلّمة والخصومات',
            descriptionEn: 'Delivered box settlements and deductions',
            route: '/admin/finance/settlements',
            icon: 'lucideReceipt',
          },
          {
            id: 'reports',
            labelAr: 'التقارير المالية',
            labelEn: 'Financial Reports',
            descriptionAr: 'تقارير الإيرادات والعمولات والربحية',
            descriptionEn: 'Revenue, commission, and profitability reports',
            route: '/admin/finance/reports',
            icon: 'lucideFileText',
          },
        ],
      },
    ],
  },
  {
    id: 'support',
    labelAr: 'الدعم',
    labelEn: 'Support',
    items: [
      {
        id: 'support-group',
        labelAr: 'خدمة العملاء',
        labelEn: 'Customer Care',
        icon: 'lucideLifeBuoy',
        children: [
          {
            id: 'complaints',
            labelAr: 'الشكاوى',
            labelEn: 'Complaints',
            descriptionAr: 'متابعة الشكاوى والتعويضات',
            descriptionEn: 'Track complaints and compensations',
            route: '/admin/support/complaints',
            icon: 'lucideMessageSquare',
            badge: 8,
          },
          {
            id: 'wallet',
            labelAr: 'المحفظة',
            labelEn: 'Wallet',
            descriptionAr: 'تعديلات الرصيد والاسترداد للمحفظة',
            descriptionEn: 'Wallet balance adjustments and refunds',
            route: '/admin/support/wallet',
            icon: 'lucideCreditCard',
          },
        ],
      },
    ],
  },
  {
    id: 'security',
    labelAr: 'الأمان والصلاحيات',
    labelEn: 'Security',
    items: [
      {
        id: 'security-workspace',
        labelAr: 'مساحة الأمان',
        labelEn: 'Security workspace',
        descriptionAr: 'الأدوار والصلاحيات والمستخدمون في مساحة واحدة',
        descriptionEn: 'Roles, permissions, and users in one workspace',
        route: '/admin/security',
        icon: 'lucideShieldAlert',
        badge: 48,
      },
    ],
  },
  {
    id: 'settings',
    labelAr: 'الإعدادات',
    labelEn: 'Settings',
    items: [
      {
        id: 'settings-group',
        labelAr: 'النظام',
        labelEn: 'System',
        icon: 'lucideSettings',
        children: [
          {
            id: 'areas',
            labelAr: 'المناطق والتغطية',
            labelEn: 'Areas & Coverage',
            descriptionAr: 'إدارة مناطق الخدمة والتغطية',
            descriptionEn: 'Manage service areas and coverage',
            route: '/admin/settings/areas',
            icon: 'lucideMapPin',
          },
          {
            id: 'global-settings',
            labelAr: 'إعدادات عامة',
            labelEn: 'Global Settings',
            descriptionAr: 'إعدادات المنصة والعمولات الافتراضية',
            descriptionEn: 'Platform defaults and commission settings',
            route: '/admin/settings/general',
            icon: 'lucideSlidersHorizontal',
          },
        ],
      },
    ],
  },
];

export const ADMIN_NAV_ITEMS: AdminNavItem[] = ADMIN_NAV_SECTIONS.flatMap(
  (section) => section.items,
);

export const ADMIN_QUICK_ACTION: AdminNavItem = {
  id: 'quick-exception',
  labelAr: 'استثناء طارئ',
  labelEn: 'Quick Exception',
  route: '/admin/operations/audit',
  icon: 'lucidePlus',
};
