import { AdminNavItem, AdminNavSection } from './admin-nav.model';

export const ADMIN_NAV_SECTIONS: AdminNavSection[] = [
  {
    id: 'main',
    labelAr: 'الرئيسية',
    labelEn: 'Main',
    items: [
      {
        id: 'overview',
        labelAr: 'نظرة عامة',
        labelEn: 'Overview',
        descriptionAr: 'مؤشرات اليوم وملخص العمليات',
        descriptionEn: 'Daily KPIs and operations summary',
        route: '/admin/overview',
        icon: 'lucideLayoutDashboard',
      },
    ],
  },
  {
    id: 'accounts',
    labelAr: 'الحسابات',
    labelEn: 'Accounts',
    items: [
      {
        id: 'accounts-group',
        labelAr: 'إدارة الحسابات',
        labelEn: 'Account Management',
        icon: 'lucideUsers',
        children: [
          {
            id: 'pending-accounts',
            labelAr: 'طلبات قيد المراجعة',
            labelEn: 'Pending Review',
            descriptionAr: 'مراجعة واعتماد حسابات المطاعم والسائقين',
            descriptionEn: 'Review and approve restaurant and driver accounts',
            route: '/admin/accounts/pending',
            icon: 'lucideUserCheck',
            badge: 12,
          },
          {
            id: 'restaurants',
            labelAr: 'المطاعم',
            labelEn: 'Restaurants',
            descriptionAr: 'إدارة حالة المطاعم والوثائق',
            descriptionEn: 'Manage restaurant status and documents',
            route: '/admin/accounts/restaurants',
            icon: 'lucideStore',
          },
          {
            id: 'drivers',
            labelAr: 'السائقون',
            labelEn: 'Drivers',
            descriptionAr: 'التحقق من السائقين وحالة العمل',
            descriptionEn: 'Driver verification and work status',
            route: '/admin/accounts/drivers',
            icon: 'lucideTruck',
            badge: 4,
          },
          {
            id: 'customers',
            labelAr: 'العملاء',
            labelEn: 'Customers',
            descriptionAr: 'إدارة حسابات العملاء والاشتراكات',
            descriptionEn: 'Manage customer accounts and subscriptions',
            route: '/admin/accounts/customers',
            icon: 'lucideContactRound',
          },
          {
            id: 'documents-hub',
            labelAr: 'مركز الوثائق',
            labelEn: 'Documents Hub',
            descriptionAr: 'مراجعة واعتماد وثائق المطاعم والسائقين',
            descriptionEn: 'Review and approve restaurant and driver documents',
            route: '/admin/accounts/documents',
            icon: 'lucideFolderOpen',
          },
        ],
      },
    ],
  },
  {
    id: 'operations',
    labelAr: 'العمليات',
    labelEn: 'Operations',
    items: [
      {
        id: 'operations-group',
        labelAr: 'مركز العمليات',
        labelEn: 'Operations Hub',
        icon: 'lucideClock',
        children: [
          {
            id: 'orders',
            labelAr: 'الطلبات',
            labelEn: 'Orders',
            descriptionAr: 'مركز موحّد للطلبات — فلاتر حسب المرحلة وإجراءات التدخل',
            descriptionEn: 'Unified orders hub — phase filters and intervention actions',
            route: '/admin/operations/orders',
            icon: 'lucidePackage',
            badge: 5,
          },
          {
            id: 'delivery',
            labelAr: 'التوصيل',
            labelEn: 'Delivery',
            descriptionAr: 'تتبع مباشر وحالات Hold',
            descriptionEn: 'Live tracking and hold cases',
            route: '/admin/operations/delivery',
            icon: 'lucideMapPinned',
            badge: 4,
          },
          {
            id: 'audit',
            labelAr: 'سجل الاستثناءات',
            labelEn: 'Exception Audit',
            descriptionAr: 'سجل تدقيق للإجراءات داخل نافذة 72h',
            descriptionEn: 'Audit log for in-window admin actions',
            route: '/admin/operations/audit',
            icon: 'lucideShieldAlert',
            badge: 1,
          },
          {
            id: 'capacity',
            labelAr: 'السعة و Busy',
            labelEn: 'Capacity & Busy',
            descriptionAr: 'مراقبة الطاقة الاستيعابية وحالة الانشغال',
            descriptionEn: 'Monitor restaurant capacity and busy status',
            route: '/admin/operations/capacity',
            icon: 'lucideGauge',
          },
          {
            id: 'auto-selection',
            labelAr: 'الاختيار التلقائي',
            labelEn: 'Auto Selection',
            descriptionAr: 'ضبط الاختيار التلقائي وحد التكرار للمطاعم',
            descriptionEn: 'Auto-selection rules and restaurant repetition limits',
            route: '/admin/operations/auto-selection',
            icon: 'lucideWandSparkles',
          },
          {
            id: 'invoices',
            labelAr: 'الفواتير والملصقات',
            labelEn: 'Invoices & Labels',
            descriptionAr: 'إعداد الفواتير والباركود وملصقات التوصيل',
            descriptionEn: 'Invoices, barcodes, and delivery labels',
            route: '/admin/operations/invoices',
            icon: 'lucideQrCode',
          },
          {
            id: 'menus',
            labelAr: 'اعتماد القوائم',
            labelEn: 'Menu Approval',
            descriptionAr: 'مراجعة واعتماد قوائم ووجبات المطاعم',
            descriptionEn: 'Review and approve restaurant menus and meals',
            route: '/admin/operations/menus',
            icon: 'lucideUtensils',
          },
        ],
      },
    ],
  },
  {
    id: 'subscriptions',
    labelAr: 'الاشتراكات والتسعير',
    labelEn: 'Subscriptions & Pricing',
    items: [
      {
        id: 'subscriptions-group',
        labelAr: 'الاشتراكات',
        labelEn: 'Subscriptions',
        icon: 'lucideTags',
        children: [
          {
            id: 'programs',
            labelAr: 'البرامج والباقات',
            labelEn: 'Programs & Bundles',
            descriptionAr: 'إدارة البرامج والباقات والمدد',
            descriptionEn: 'Manage programs, bundles, and durations',
            route: '/admin/subscriptions/programs',
            icon: 'lucideLayers',
          },
          {
            id: 'tiers',
            labelAr: 'تصنيف المطاعم',
            labelEn: 'Restaurant Tiers',
            descriptionAr: 'Basic / Platinum / Elite حسب السعر',
            descriptionEn: 'Basic / Platinum / Elite by price band',
            route: '/admin/subscriptions/tiers',
            icon: 'lucideAward',
          },
          {
            id: 'pricing',
            labelAr: 'التسعير والعمولات',
            labelEn: 'Pricing & Commissions',
            descriptionAr: 'سياسة التسعير وعمولة المنصة',
            descriptionEn: 'Pricing policy and platform commission',
            route: '/admin/subscriptions/pricing',
            icon: 'lucidePercent',
          },
          {
            id: 'family',
            labelAr: 'الاشتراك العائلي',
            labelEn: 'Family Subscriptions',
            descriptionAr: 'متابعة المجموعات العائلية والأفراد والحصص',
            descriptionEn: 'Monitor family groups, members, and quotas',
            route: '/admin/subscriptions/family',
            icon: 'lucideUsersRound',
          },
          {
            id: 'freeze',
            labelAr: 'التجميد',
            labelEn: 'Freeze Management',
            descriptionAr: 'إدارة طلبات تجميد الاشتراك والموافقات',
            descriptionEn: 'Manage subscription freeze requests and approvals',
            route: '/admin/subscriptions/freeze',
            icon: 'lucideSnowflake',
          },
          {
            id: 'renewals',
            labelAr: 'التجديد',
            labelEn: 'Renewals',
            descriptionAr: 'متابعة تجديد الاشتراكات والتنبيهات',
            descriptionEn: 'Track subscription renewals and reminders',
            route: '/admin/subscriptions/renewals',
            icon: 'lucideRefreshCw',
          },
          {
            id: 'upgrades',
            labelAr: 'ترقية التصنيف',
            labelEn: 'Tier Upgrades',
            descriptionAr: 'ترقية تصنيف الاشتراك ومعاينة السعر',
            descriptionEn: 'Subscription tier upgrades and price preview',
            route: '/admin/subscriptions/upgrades',
            icon: 'lucideTrendingUp',
          },
        ],
      },
    ],
  },
  {
    id: 'marketing',
    labelAr: 'التسويق والإحالات',
    labelEn: 'Marketing',
    items: [
      {
        id: 'marketing-group',
        labelAr: 'مركز التسويق',
        labelEn: 'Marketing Hub',
        icon: 'lucideMegaphone',
        children: [
          {
            id: 'marketing-influencers',
            labelAr: 'المؤثرون',
            labelEn: 'Influencers',
            descriptionAr: 'إدارة ملفات المؤثرين واللينك والكود',
            descriptionEn: 'Manage influencer profiles, links, and codes',
            route: '/admin/marketing/influencers',
            icon: 'lucideUserRound',
            badge: 2,
          },
          {
            id: 'marketing-campaigns',
            labelAr: 'الحملات',
            labelEn: 'Campaigns',
            descriptionAr: 'حملات خصم تشاركية مع المطاعم',
            descriptionEn: 'Collaborative discount campaigns with restaurants',
            route: '/admin/marketing/campaigns',
            icon: 'lucideTarget',
          },
          {
            id: 'marketing-promo',
            labelAr: 'أكواد الخصم',
            labelEn: 'Promo Codes',
            descriptionAr: 'أكواد المؤثرين والحملات والإحالة',
            descriptionEn: 'Influencer, campaign, and referral codes',
            route: '/admin/marketing/promo-codes',
            icon: 'lucideTicket',
          },
          {
            id: 'marketing-referrals',
            labelAr: 'الإحالات',
            labelEn: 'Referrals',
            descriptionAr: 'برنامج الإحالة ومكافآت المُحيل والمُحال',
            descriptionEn: 'Referral program and referrer/referee rewards',
            route: '/admin/marketing/referrals',
            icon: 'lucideShare2',
          },
          {
            id: 'marketing-ads',
            labelAr: 'الإعلانات والمزايدات',
            labelEn: 'Ads & Bidding',
            descriptionAr: 'إدارة أماكن الإعلان ومزايدات المطاعم',
            descriptionEn: 'Ad placements and restaurant bidding',
            route: '/admin/marketing/ads',
            icon: 'lucideRadio',
          },
          {
            id: 'marketing-reports',
            labelAr: 'التقارير والعمولات',
            labelEn: 'Reports & Commissions',
            descriptionAr: 'تقارير الاستخدام والعمولات المستحقة',
            descriptionEn: 'Usage reports and pending commissions',
            route: '/admin/marketing/reports',
            icon: 'lucideChartBar',
          },
        ],
      },
    ],
  },
  {
    id: 'finance',
    labelAr: 'المالية',
    labelEn: 'Finance',
    items: [
      {
        id: 'finance-group',
        labelAr: 'المحاسبة',
        labelEn: 'Accounting',
        icon: 'lucideWallet',
        children: [
          {
            id: 'cancellations',
            labelAr: 'الإلغاء والاسترداد',
            labelEn: 'Cancellations & Refunds',
            descriptionAr: 'مراجعة طلبات الإلغاء وحساب الاسترداد',
            descriptionEn: 'Review cancellations and refund calculations',
            route: '/admin/finance/cancellations',
            icon: 'lucideUndo2',
            badge: 5,
          },
          {
            id: 'settlements',
            labelAr: 'تسويات المطاعم',
            labelEn: 'Restaurant Settlements',
            descriptionAr: 'تسويات الصناديق المسلّمة والخصومات',
            descriptionEn: 'Delivered box settlements and deductions',
            route: '/admin/finance/settlements',
            icon: 'lucideReceipt',
          },
          {
            id: 'reports',
            labelAr: 'التقارير المالية',
            labelEn: 'Financial Reports',
            descriptionAr: 'تقارير الإيرادات والعمولات والربحية',
            descriptionEn: 'Revenue, commission, and profitability reports',
            route: '/admin/finance/reports',
            icon: 'lucideFileText',
          },
        ],
      },
    ],
  },
  {
    id: 'support',
    labelAr: 'الدعم',
    labelEn: 'Support',
    items: [
      {
        id: 'support-group',
        labelAr: 'خدمة العملاء',
        labelEn: 'Customer Care',
        icon: 'lucideLifeBuoy',
        children: [
          {
            id: 'complaints',
            labelAr: 'الشكاوى',
            labelEn: 'Complaints',
            descriptionAr: 'متابعة الشكاوى والتعويضات',
            descriptionEn: 'Track complaints and compensations',
            route: '/admin/support/complaints',
            icon: 'lucideMessageSquare',
            badge: 8,
          },
          {
            id: 'wallet',
            labelAr: 'المحفظة',
            labelEn: 'Wallet',
            descriptionAr: 'تعديلات الرصيد والاسترداد للمحفظة',
            descriptionEn: 'Wallet balance adjustments and refunds',
            route: '/admin/support/wallet',
            icon: 'lucideCreditCard',
          },
          {
            id: 'loyalty',
            labelAr: 'الولاء والمكافآت',
            labelEn: 'Loyalty & Rewards',
            descriptionAr: 'إدارة نقاط الولاء والمكافآت والاستبدال',
            descriptionEn: 'Manage loyalty points, rewards, and redemption',
            route: '/admin/support/loyalty',
            icon: 'lucideGift',
          },
          {
            id: 'ratings',
            labelAr: 'التقييمات',
            labelEn: 'Ratings & Reviews',
            descriptionAr: 'متابعة تقييمات العملاء والمطاعم والسائقين',
            descriptionEn: 'Monitor customer, restaurant, and driver ratings',
            route: '/admin/support/ratings',
            icon: 'lucideStar',
          },
        ],
      },
    ],
  },
  {
    id: 'security',
    labelAr: 'الأمان والصلاحيات',
    labelEn: 'Security',
    items: [
      {
        id: 'security-workspace',
        labelAr: 'مساحة الأمان',
        labelEn: 'Security workspace',
        descriptionAr: 'الأدوار والصلاحيات والمستخدمون في مساحة واحدة',
        descriptionEn: 'Roles, permissions, and users in one workspace',
        route: '/admin/security',
        icon: 'lucideShieldAlert',
        badge: 48,
      },
    ],
  },
  {
    id: 'settings',
    labelAr: 'الإعدادات',
    labelEn: 'Settings',
    items: [
      {
        id: 'settings-group',
        labelAr: 'النظام',
        labelEn: 'System',
        icon: 'lucideSettings',
        children: [
          {
            id: 'areas',
            labelAr: 'المناطق والتغطية',
            labelEn: 'Areas & Coverage',
            descriptionAr: 'إدارة مناطق الخدمة والتغطية',
            descriptionEn: 'Manage service areas and coverage',
            route: '/admin/settings/areas',
            icon: 'lucideMapPin',
          },
          {
            id: 'global-settings',
            labelAr: 'إعدادات عامة',
            labelEn: 'Global Settings',
            descriptionAr: 'إعدادات المنصة والعمولات الافتراضية',
            descriptionEn: 'Platform defaults and commission settings',
            route: '/admin/settings/general',
            icon: 'lucideSlidersHorizontal',
          },
          {
            id: 'exit-policy',
            labelAr: 'إنهاء التعاقد',
            labelEn: 'Exit Policy',
            descriptionAr: 'سياسة إنهاء تعاقد المطاعم والسائقين',
            descriptionEn: 'Restaurant and driver contract termination policy',
            route: '/admin/settings/exit-policy',
            icon: 'lucideDoorOpen',
          },
          {
            id: 'communication',
            labelAr: 'قنوات التواصل',
            labelEn: 'Communication Channels',
            descriptionAr: 'واتساب والإشعارات وقنوات التواصل',
            descriptionEn: 'WhatsApp, notifications, and messaging channels',
            route: '/admin/settings/communication',
            icon: 'lucideMessagesSquare',
          },
          {
            id: 'languages',
            labelAr: 'تعدد اللغات',
            labelEn: 'Languages',
            descriptionAr: 'إدارة اللغات والترجمات في المنصة',
            descriptionEn: 'Manage platform languages and translations',
            route: '/admin/settings/languages',
            icon: 'lucideLanguages',
          },
          {
            id: 'privacy',
            labelAr: 'الخصوصية',
            labelEn: 'Privacy',
            descriptionAr: 'سياسات حماية الخصوصية وقواعد إخفاء البيانات',
            descriptionEn: 'Privacy policies and data masking rules',
            route: '/admin/settings/privacy',
            icon: 'lucideEyeOff',
          },
          {
            id: 'multitenancy',
            labelAr: 'التوسع الدولي',
            labelEn: 'Multi-Tenancy',
            descriptionAr: 'إدارة الدول والمستأجرين و Super Admin',
            descriptionEn: 'Countries, tenants, and super admin scope',
            route: '/admin/settings/multitenancy',
            icon: 'lucideGlobe',
          },
        ],
      },
    ],
  },
];

export const ADMIN_NAV_ITEMS: AdminNavItem[] = ADMIN_NAV_SECTIONS.flatMap(
  (section) => section.items,
);

export const ADMIN_QUICK_ACTION: AdminNavItem = {
  id: 'quick-exception',
  labelAr: 'استثناء طارئ',
  labelEn: 'Quick Exception',
  route: '/admin/operations/audit',
  icon: 'lucidePlus',
};
