import { Component, computed, inject, signal } from '@angular/core';
import { DecimalPipe, NgClass } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideAlarmClock, lucideCheck, lucideChevronDown, lucideCircleAlert, lucideClock3, lucideHeadphones, lucideImage, lucideMessageSquare, lucideSearch, lucideShieldCheck, lucideStar, lucideTrendingUp, lucideUserRound, lucideWalletCards, lucideX } from '@ng-icons/lucide';
import { AppLocaleService } from '@/core/i18n/app-locale.service';
import { MmTablePaginationComponent } from '@/shared/components/layout/table-pagination';
import { createTablePagination } from '@/shared/utils/table-pagination.util';

type Tab='complaints'|'support'|'sla'; type Status='new'|'review'|'waiting'|'resolved'|'rejected'; type Priority='critical'|'high'|'medium'|'low';
type Ticket={id:string;kind:'complaint'|'support';customerAr:string;customerEn:string;subjectAr:string;subjectEn:string;categoryAr:string;categoryEn:string;restaurant?:string;order?:string;priority:Priority;status:Status;created:string;slaHours:number;ageHours:number;amount:number;hasEvidence:boolean;descriptionAr:string;descriptionEn:string;assignedAr:string;assignedEn:string};
const TICKETS:Ticket[]=[
 {id:'C-482',kind:'complaint',customerAr:'أحمد السالم',customerEn:'Ahmed Al-Salem',subjectAr:'وجبة غير مطابقة للطلب',subjectEn:'Incorrect meal delivered',categoryAr:'جودة الوجبة',categoryEn:'Meal quality',restaurant:'Fit Meals Co.',order:'ORD-82914',priority:'critical',status:'new',created:'2026-07-01 09:20',slaHours:4,ageHours:3.4,amount:8.5,hasEvidence:true,descriptionAr:'الوجبة المستلمة مختلفة عن الوجبة المحددة وتحتوي على مكونات غير مطلوبة.',descriptionEn:'Delivered meal differs from the selected meal and contains unrequested ingredients.',assignedAr:'فريق الجودة',assignedEn:'Quality team'},
 {id:'C-481',kind:'complaint',customerAr:'سارة محمد',customerEn:'Sara Mohamed',subjectAr:'مكونات ناقصة',subjectEn:'Missing ingredients',categoryAr:'جودة الوجبة',categoryEn:'Meal quality',restaurant:'Green Kitchen',order:'ORD-82896',priority:'high',status:'review',created:'2026-07-01 08:10',slaHours:8,ageHours:5.2,amount:6.75,hasEvidence:true,descriptionAr:'ينقص الوجبة البروتين والصوص الموضحان في القائمة.',descriptionEn:'Meal is missing the protein and sauce shown on the menu.',assignedAr:'نور العتيبي',assignedEn:'Nour Al-Otaibi'},
 {id:'T-390',kind:'support',customerAr:'خالد علي',customerEn:'Khaled Ali',subjectAr:'تعذر استخدام رصيد المحفظة',subjectEn:'Cannot use wallet balance',categoryAr:'المحفظة',categoryEn:'Wallet',priority:'high',status:'waiting',created:'2026-06-30 18:40',slaHours:12,ageHours:9.1,amount:24,hasEvidence:false,descriptionAr:'رصيد المحفظة ظاهر ولكن لا يمكن استخدامه عند الدفع.',descriptionEn:'Wallet balance is visible but cannot be used at checkout.',assignedAr:'الدعم المالي',assignedEn:'Finance support'},
 {id:'C-479',kind:'complaint',customerAr:'منى إبراهيم',customerEn:'Mona Ibrahim',subjectAr:'تأخر توصيل متكرر',subjectEn:'Repeated delivery delay',categoryAr:'التوصيل',categoryEn:'Delivery',restaurant:'Daily Balance',order:'ORD-82780',priority:'medium',status:'review',created:'2026-06-30 13:15',slaHours:24,ageHours:16,amount:4.5,hasEvidence:true,descriptionAr:'وصل الطلب متأخرًا أكثر من ساعة للمرة الثالثة.',descriptionEn:'Order arrived over an hour late for the third time.',assignedAr:'فريق التوصيل',assignedEn:'Delivery team'},
 {id:'T-388',kind:'support',customerAr:'يوسف حسن',customerEn:'Youssef Hassan',subjectAr:'مشكلة في تجديد الاشتراك',subjectEn:'Subscription renewal issue',categoryAr:'الاشتراكات',categoryEn:'Subscriptions',priority:'medium',status:'new',created:'2026-06-30 11:05',slaHours:24,ageHours:18,amount:0,hasEvidence:false,descriptionAr:'تم الخصم ولم يتم تمديد تاريخ الاشتراك.',descriptionEn:'Payment was charged but subscription date was not extended.',assignedAr:'دعم الاشتراكات',assignedEn:'Subscription support'},
 {id:'C-475',kind:'complaint',customerAr:'فاطمة عادل',customerEn:'Fatma Adel',subjectAr:'تلف عبوة الوجبة',subjectEn:'Damaged meal package',categoryAr:'التغليف',categoryEn:'Packaging',restaurant:'Protein House',order:'ORD-82542',priority:'low',status:'resolved',created:'2026-06-29 10:30',slaHours:24,ageHours:6,amount:7.25,hasEvidence:true,descriptionAr:'العبوة وصلت مفتوحة وتم تعويض العميل.',descriptionEn:'Package arrived open and customer was compensated.',assignedAr:'ريم خالد',assignedEn:'Reem Khaled'},
 {id:'T-382',kind:'support',customerAr:'عمر سامي',customerEn:'Omar Samy',subjectAr:'تغيير عنوان التوصيل',subjectEn:'Change delivery address',categoryAr:'الحساب',categoryEn:'Account',priority:'low',status:'resolved',created:'2026-06-28 15:00',slaHours:24,ageHours:2,amount:0,hasEvidence:false,descriptionAr:'طلب تحديث عنوان التوصيل للأسبوع القادم.',descriptionEn:'Requested delivery address update for next week.',assignedAr:'مي أحمد',assignedEn:'Mai Ahmed'},
 {id:'C-472',kind:'complaint',customerAr:'نورة خالد',customerEn:'Noura Khaled',subjectAr:'حساسية غير مراعاة',subjectEn:'Allergy preference ignored',categoryAr:'سلامة غذائية',categoryEn:'Food safety',restaurant:'Lean Meals',order:'ORD-82211',priority:'critical',status:'waiting',created:'2026-06-27 12:45',slaHours:2,ageHours:28,amount:9,hasEvidence:true,descriptionAr:'الوجبة تحتوي على مكسرات رغم تسجيل الحساسية.',descriptionEn:'Meal contained nuts despite the registered allergy.',assignedAr:'مدير الجودة',assignedEn:'Quality manager'},
];

@Component({selector:'mm-complaints-support-page',standalone:true,imports:[DecimalPipe,NgClass,FormsModule,NgIcon,MmTablePaginationComponent],providers:[provideIcons({lucideAlarmClock,lucideCheck,lucideChevronDown,lucideCircleAlert,lucideClock3,lucideHeadphones,lucideImage,lucideMessageSquare,lucideSearch,lucideShieldCheck,lucideStar,lucideTrendingUp,lucideUserRound,lucideWalletCards,lucideX})],templateUrl:'./complaints-support-page.component.html',styleUrl:'./complaints-support-page.component.scss',host:{class:'block'}})
export class ComplaintsSupportPageComponent{
 readonly locale=inject(AppLocaleService);readonly tab=signal<Tab>('complaints');readonly status=signal<'all'|Status>('all');readonly priority=signal<'all'|Priority>('all');readonly search=signal('');readonly selected=signal<Ticket|null>(null);readonly rows=signal<Ticket[]>(TICKETS);readonly compensation=signal<'wallet'|'extension'>('wallet');readonly toast=signal('');readonly refreshing=signal(false);readonly pg=createTablePagination(6);readonly currentPage=this.pg.currentPage;readonly pageSize=this.pg.pageSize;
 readonly t=computed(()=>this.locale.isRtl()?{complaints:'الشكاوى',support:'تذاكر الدعم',sla:'الأداء و SLA',open:'شكاوى مفتوحة',critical:'تصعيدات حرجة',resolved:'مغلقة اليوم',slaRate:'الالتزام بـ SLA',all:'كل الحالات',allPriorities:'كل الأولويات',new:'جديدة',review:'قيد المراجعة',waiting:'بانتظار رد',resolvedStatus:'تم الحل',rejected:'مرفوضة',criticalP:'حرجة',high:'عالية',medium:'متوسطة',low:'منخفضة',search:'ابحث برقم التذكرة أو العميل أو الطلب...',queue:'صندوق الشكاوى والدعم',queueSub:'مراجعة الأدلة والتعويضات والتصعيدات من مكان واحد',ticket:'التذكرة',customer:'العميل',subject:'الموضوع',priority:'الأولوية',status:'الحالة',slaCol:'الوقت المتبقي',assigned:'المسؤول',action:'إجراء',details:'التفاصيل',items:'تذكرة',noData:'لا توجد تذاكر مطابقة',hours:'س',breached:'متجاوز',evidence:'الأدلة والصور',hasEvidence:'صور مرفقة',noEvidence:'بدون صور',order:'الطلب',restaurant:'المطعم',description:'وصف المشكلة',compensation:'قرار التعويض',wallet:'رد قيمة الوجبة للمحفظة',extension:'تمديد الاشتراك يومًا',validate:'تأكيد الشكوى وتنفيذ التعويض',reject:'رفض الشكوى',resolve:'إغلاق كتذكرة محلولة',close:'إغلاق',done:'تم تحديث التذكرة بنجاح',slaTitle:'مراقبة اتفاقية مستوى الخدمة',slaSub:'توزيع التذاكر حسب زمن الاستجابة',satisfaction:'رضا العملاء',avgResolution:'متوسط وقت الحل'}:{complaints:'Complaints',support:'Support tickets',sla:'Performance & SLA',open:'Open complaints',critical:'Critical escalations',resolved:'Resolved today',slaRate:'SLA compliance',all:'All statuses',allPriorities:'All priorities',new:'New',review:'Under review',waiting:'Waiting response',resolvedStatus:'Resolved',rejected:'Rejected',criticalP:'Critical',high:'High',medium:'Medium',low:'Low',search:'Search ticket, customer, or order...',queue:'Complaints & support inbox',queueSub:'Review evidence, compensation, and escalation in one place',ticket:'Ticket',customer:'Customer',subject:'Subject',priority:'Priority',status:'Status',slaCol:'Time left',assigned:'Assignee',action:'Action',details:'Details',items:'tickets',noData:'No matching tickets',hours:'h',breached:'Breached',evidence:'Evidence & photos',hasEvidence:'Photos attached',noEvidence:'No photos',order:'Order',restaurant:'Restaurant',description:'Issue description',compensation:'Compensation decision',wallet:'Refund meal value to wallet',extension:'Extend subscription by one day',validate:'Validate & compensate',reject:'Reject complaint',resolve:'Resolve ticket',close:'Close',done:'Ticket updated successfully',slaTitle:'Service level monitoring',slaSub:'Ticket distribution by response time',satisfaction:'Customer satisfaction',avgResolution:'Avg resolution time'});
 readonly filtered=computed(()=>{const q=this.search().toLowerCase().trim(),kind=this.tab()==='support'?'support':this.tab()==='complaints'?'complaint':null;return this.rows().filter(x=>(!kind||x.kind===kind)&&(this.status()==='all'||x.status===this.status())&&(this.priority()==='all'||x.priority===this.priority())&&(!q||x.id.toLowerCase().includes(q)||x.customerAr.toLowerCase().includes(q)||x.customerEn.toLowerCase().includes(q)||x.order?.toLowerCase().includes(q)))});readonly paginated=this.pg.paginated(this.filtered);readonly totalPages=this.pg.totalPages(this.filtered);
 readonly stats=computed(()=>({open:this.rows().filter(x=>!['resolved','rejected'].includes(x.status)).length,critical:this.rows().filter(x=>x.priority==='critical'&&x.status!=='resolved').length,resolved:this.rows().filter(x=>x.status==='resolved').length,sla:Math.round(this.rows().filter(x=>x.ageHours<=x.slaHours).length/this.rows().length*100)}));
 switchTab(x:Tab){this.tab.set(x);this.animate()} animate(){this.pg.resetPage();this.refreshing.set(false);requestAnimationFrame(()=>this.refreshing.set(true));setTimeout(()=>this.refreshing.set(false),450)} name(x:Ticket){return this.locale.isRtl()?x.customerAr:x.customerEn} subject(x:Ticket){return this.locale.isRtl()?x.subjectAr:x.subjectEn} assigned(x:Ticket){return this.locale.isRtl()?x.assignedAr:x.assignedEn} category(x:Ticket){return this.locale.isRtl()?x.categoryAr:x.categoryEn} description(x:Ticket){return this.locale.isRtl()?x.descriptionAr:x.descriptionEn}
 statusLabel(s:Status){const t=this.t();return s==='new'?t.new:s==='review'?t.review:s==='waiting'?t.waiting:s==='resolved'?t.resolvedStatus:t.rejected} priorityLabel(p:Priority){const t=this.t();return p==='critical'?t.criticalP:p==='high'?t.high:p==='medium'?t.medium:t.low}
 statusTone(s:Status){return s==='resolved'?'bg-emerald-50 text-emerald-700':s==='rejected'?'bg-slate-100 text-slate-600':s==='new'?'bg-sky-50 text-sky-700':s==='waiting'?'bg-violet-50 text-violet-700':'bg-amber-50 text-amber-700'} priorityTone(p:Priority){return p==='critical'?'bg-rose-50 text-rose-700':p==='high'?'bg-orange-50 text-orange-700':p==='medium'?'bg-amber-50 text-amber-700':'bg-slate-50 text-slate-600'}
 update(x:Ticket,status:Status){this.rows.update(rows=>rows.map(r=>r.id===x.id?{...r,status}:r));this.selected.set(null);this.toast.set(this.t().done);setTimeout(()=>this.toast.set(''),2200)} onPageChange(p:number){this.pg.onPageChange(p,this.totalPages())}
}
