import { Component, computed, inject, signal } from '@angular/core';
import { DecimalPipe, NgClass } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideArrowDownLeft, lucideArrowUpRight, lucideBanknote, lucideBellRing, lucideCalendarDays, lucideChartNoAxesCombined, lucideChartPie, lucideChevronDown, lucideCircleAlert, lucideCircleDollarSign, lucideDownload, lucideEye, lucideFileText, lucideLandmark, lucideReceipt, lucideRotateCcw, lucideSave, lucideSearch, lucideSettings2, lucideShieldCheck, lucideTrendingDown, lucideTrendingUp, lucideWalletCards, lucideX } from '@ng-icons/lucide';
import { AppLocaleService } from '@/core/i18n/app-locale.service';
import { MmTablePaginationComponent } from '@/shared/components/layout/table-pagination';
import { createTablePagination } from '@/shared/utils/table-pagination.util';

type Tab = 'overview'|'revenue'|'expenses'|'profitability'|'cashflow';
type Detail = { key:string; ar:string; en:string; value:number; previous:number; tone:string; icon:string; items:{ar:string;en:string;amount:number;noteAr:string;noteEn:string}[] };
const DETAILS:Detail[]=[
 {key:'subscriptions',ar:'إيرادات الاشتراكات',en:'Subscription revenue',value:48260,previous:41750,tone:'emerald',icon:'lucideWalletCards',items:[{ar:'اشتراكات شهرية',en:'Monthly plans',amount:22140,noteAr:'412 اشتراك',noteEn:'412 subscriptions'},{ar:'اشتراكات ربع سنوية',en:'Quarterly plans',amount:16820,noteAr:'146 اشتراك',noteEn:'146 subscriptions'},{ar:'اشتراكات سنوية',en:'Annual plans',amount:9300,noteAr:'38 اشتراك',noteEn:'38 subscriptions'}]},
 {key:'commissions',ar:'عمولات المنصة',en:'Platform commissions',value:12840,previous:10920,tone:'emerald',icon:'lucideCircleDollarSign',items:[{ar:'عمولات المطاعم',en:'Restaurant commissions',amount:7290,noteAr:'متوسط 12.4%',noteEn:'12.4% average'},{ar:'عمولات الاشتراكات',en:'Subscription commissions',amount:3810,noteAr:'حسب مدة الخطة',noteEn:'By plan duration'},{ar:'التوصيل والحملات',en:'Delivery & campaigns',amount:1740,noteAr:'رسوم متغيرة',noteEn:'Variable fees'}]},
 {key:'service',ar:'رسوم الخدمات',en:'Service fees',value:3940,previous:3510,tone:'sky',icon:'lucideReceipt',items:[{ar:'رسوم الدفع الإلكتروني',en:'Online payment fees',amount:1720,noteAr:'1,842 عملية',noteEn:'1,842 payments'},{ar:'رسوم تشغيلية',en:'Processing fees',amount:1380,noteAr:'تشغيل الطلبات',noteEn:'Order processing'},{ar:'خدمات الشركات',en:'Corporate services',amount:840,noteAr:'9 حسابات',noteEn:'9 accounts'}]},
 {key:'restaurants',ar:'مستحقات المطاعم',en:'Restaurant payouts',value:31650,previous:28420,tone:'rose',icon:'lucideLandmark',items:[{ar:'تسويات مدفوعة',en:'Paid settlements',amount:24580,noteAr:'23 مطعمًا',noteEn:'23 restaurants'},{ar:'تسويات معلّقة',en:'Pending settlements',amount:5890,noteAr:'6 مطاعم',noteEn:'6 restaurants'},{ar:'تعديلات تسوية',en:'Settlement adjustments',amount:1180,noteAr:'خصومات وتسويات',noteEn:'Deductions & adjustments'}]},
 {key:'delivery',ar:'تكاليف التوصيل',en:'Delivery costs',value:8640,previous:7920,tone:'amber',icon:'lucideTrendingDown',items:[{ar:'أجور السائقين',en:'Driver payouts',amount:6120,noteAr:'3,420 توصيلة',noteEn:'3,420 deliveries'},{ar:'حوافز الأداء',en:'Performance incentives',amount:1480,noteAr:'42 سائقًا',noteEn:'42 drivers'},{ar:'تعويضات تشغيلية',en:'Operational compensation',amount:1040,noteAr:'مسافات وانتظار',noteEn:'Distance & waiting'}]},
 {key:'refunds',ar:'الاستردادات والتعويضات',en:'Refunds & compensation',value:2870,previous:3340,tone:'rose',icon:'lucideArrowDownLeft',items:[{ar:'إلغاءات اشتراكات',en:'Subscription cancellations',amount:1680,noteAr:'31 طلبًا',noteEn:'31 requests'},{ar:'شكاوى جودة',en:'Quality complaints',amount:790,noteAr:'18 حالة',noteEn:'18 cases'},{ar:'تعويضات محافظ',en:'Wallet compensation',amount:400,noteAr:'12 محفظة',noteEn:'12 wallets'}]},
];
const MOVES=[
 ['TRX-9061','subscriptions','اشتراك عميل — خطة شهرية','Customer subscription — monthly plan',89,'in','2026-07-01'],['TRX-9060','restaurants','تسوية مطعم Green Kitchen','Green Kitchen settlement',1240,'out','2026-07-01'],['TRX-9059','commissions','عمولة منصة — اشتراكات','Platform commission — subscriptions',428,'in','2026-06-30'],['TRX-9058','delivery','دفعة دورة السائقين','Driver cycle payout',860,'out','2026-06-30'],['TRX-9057','service','رسوم معالجة مدفوعات','Payment processing fees',190,'in','2026-06-29'],['TRX-9056','refunds','استرداد إلغاء اشتراك','Cancellation refund',67,'out','2026-06-29'],['TRX-9055','subscriptions','اشتراك عميل — خطة سنوية','Customer subscription — annual plan',360,'in','2026-06-28'],['TRX-9054','commissions','عمولة تسوية مطاعم','Restaurant settlement commission',615,'in','2026-06-28'],['TRX-9053','restaurants','تسوية مطعم Fit Bites','Fit Bites settlement',980,'out','2026-06-27'],['TRX-9052','service','رسوم خدمة حساب شركات','Corporate account service fee',132,'in','2026-06-27']
] as const;

@Component({selector:'mm-financial-reports-page',standalone:true,imports:[DecimalPipe,NgClass,FormsModule,NgIcon,MmTablePaginationComponent],providers:[provideIcons({lucideArrowDownLeft,lucideArrowUpRight,lucideBanknote,lucideBellRing,lucideCalendarDays,lucideChartNoAxesCombined,lucideChartPie,lucideChevronDown,lucideCircleAlert,lucideCircleDollarSign,lucideDownload,lucideEye,lucideFileText,lucideLandmark,lucideReceipt,lucideRotateCcw,lucideSave,lucideSearch,lucideSettings2,lucideShieldCheck,lucideTrendingDown,lucideTrendingUp,lucideWalletCards,lucideX})],templateUrl:'./financial-reports-page.component.html',styleUrl:'./financial-reports-page.component.scss',host:{class:'block'}})
export class FinancialReportsPageComponent{
 readonly locale=inject(AppLocaleService);readonly tab=signal<Tab>('overview');readonly days=signal(30);readonly search=signal('');readonly selected=signal<Detail|null>(null);readonly refreshing=signal(false);readonly profitAlertDismissed=signal(false);readonly settingsOpen=signal(false);readonly settingsSaved=signal(false);readonly alertsEnabled=signal(true);readonly targetMargin=signal(35);readonly warningMargin=signal(32);readonly criticalMargin=signal(25);readonly expenseCap=signal(65);readonly autoReview=signal(true);readonly pg=createTablePagination(6);readonly currentPage=this.pg.currentPage;readonly pageSize=this.pg.pageSize;
 readonly t=computed(()=>this.locale.isRtl()?{overview:'الملخص التنفيذي',revenue:'الإيرادات',expenses:'المصروفات',profitability:'الربحية',cashflow:'التدفقات النقدية',last7:'آخر 7 أيام',last30:'آخر 30 يومًا',last90:'آخر 90 يومًا',export:'تصدير التقرير',totalRevenue:'إجمالي الإيرادات',totalExpenses:'إجمالي المصروفات',netProfit:'صافي الربح',margin:'هامش الربح',vs:'مقارنة بالفترة السابقة',breakdown:'التحليل المالي',breakdownSub:'تفصيل بنود الأداء المالي للمنصة',details:'عرض التفاصيل',trend:'اتجاه الأداء المالي',trendSub:'الإيرادات والمصروفات وصافي الربح',rev:'الإيرادات',exp:'المصروفات',profit:'الربح',transactions:'الحركات المالية',transactionsSub:'أحدث العمليات الداخلة والخارجة على المنصة',search:'ابحث برقم العملية أو البيان...',ref:'المرجع',statement:'البيان',category:'التصنيف',amount:'المبلغ',direction:'الاتجاه',date:'التاريخ',incoming:'وارد',outgoing:'صادر',currency:'د.ك',items:'حركة',detailTitle:'تفاصيل البند',current:'الفترة الحالية',previous:'الفترة السابقة',change:'نسبة التغير',components:'مكونات البند',close:'إغلاق',noData:'لا توجد بيانات مطابقة',alertTitle:'تنبيه الربحية',alertText:'هامش الربح أقل من الحد الآمن المحدد عند 35%',alertGap:'الفجوة عن الهدف',alertReason:'السبب الأكبر: ارتفاع تسويات المطاعم وتكاليف التوصيل',reviewProfit:'مراجعة الربحية',dismiss:'تجاهل مؤقتًا'}:{overview:'Executive summary',revenue:'Revenue',expenses:'Expenses',profitability:'Profitability',cashflow:'Cash flow',last7:'Last 7 days',last30:'Last 30 days',last90:'Last 90 days',export:'Export report',totalRevenue:'Total revenue',totalExpenses:'Total expenses',netProfit:'Net profit',margin:'Profit margin',vs:'vs previous period',breakdown:'Financial breakdown',breakdownSub:'Detailed platform financial performance',details:'View details',trend:'Financial performance trend',trendSub:'Revenue, expenses, and net profit',rev:'Revenue',exp:'Expenses',profit:'Profit',transactions:'Financial transactions',transactionsSub:'Latest platform inflows and outflows',search:'Search transaction or statement...',ref:'Reference',statement:'Statement',category:'Category',amount:'Amount',direction:'Direction',date:'Date',incoming:'Incoming',outgoing:'Outgoing',currency:'KD',items:'transactions',detailTitle:'Line item details',current:'Current period',previous:'Previous period',change:'Change',components:'Components',close:'Close',noData:'No matching data',alertTitle:'Profitability alert',alertText:'Profit margin is below the 35% safety threshold',alertGap:'Gap to target',alertReason:'Main driver: restaurant settlements and delivery costs',reviewProfit:'Review profitability',dismiss:'Dismiss for now'});
 readonly factor=computed(()=>this.days()===7?.24:this.days()===90?2.72:1);readonly revenueItems=computed(()=>DETAILS.filter(x=>['subscriptions','commissions','service'].includes(x.key)));readonly expenseItems=computed(()=>DETAILS.filter(x=>['restaurants','delivery','refunds'].includes(x.key)));
 readonly totals=computed(()=>{const f=this.factor(),rev=this.revenueItems().reduce((s,x)=>s+x.value,0)*f,exp=this.expenseItems().reduce((s,x)=>s+x.value,0)*f,profit=rev-exp;return{rev,exp,profit,margin:rev?profit/rev*100:0}});
 readonly profitAlert=computed(()=>{const margin=this.totals().margin,expenseRatio=this.totals().rev?this.totals().exp/this.totals().rev*100:0;return{active:this.alertsEnabled()&&(margin<this.targetMargin()||expenseRatio>this.expenseCap()),gap:Math.max(0,this.targetMargin()-margin),expenseRatio,severity:margin<=this.criticalMargin()?'critical':margin<=this.warningMargin()?'warning':'notice',targetProfit:this.totals().rev*this.targetMargin()/100,requiredIncrease:Math.max(0,this.totals().rev*this.targetMargin()/100-this.totals().profit)}});
 readonly visibleDetails=computed(()=>this.tab()==='revenue'?this.revenueItems():this.tab()==='expenses'?this.expenseItems():DETAILS);
 readonly moves=computed(()=>{const q=this.search().toLowerCase().trim();return MOVES.filter(x=>(this.tab()==='overview'||this.tab()==='cashflow'||(this.tab()==='revenue'&&x[5]==='in')||(this.tab()==='expenses'&&x[5]==='out')||this.tab()==='profitability')&&(!q||x[0].toLowerCase().includes(q)||(this.locale.isRtl()?x[2]:x[3]).toLowerCase().includes(q)))});readonly paginated=this.pg.paginated(this.moves);readonly totalPages=this.pg.totalPages(this.moves);
 readonly chart=computed(()=>[.62,.71,.67,.78,.74,.86,.8,.93,.88,1,.91,.97].map((v,i)=>({label:String(i*3+1),rev:Math.round(v*92),exp:Math.round(v*58+(i%3)*4),profit:Math.round(v*34)})));
 constructor(){try{const saved=JSON.parse(localStorage.getItem('mealmate-profit-settings')||'null');if(saved){this.alertsEnabled.set(saved.alertsEnabled??true);this.targetMargin.set(saved.targetMargin??35);this.warningMargin.set(saved.warningMargin??32);this.criticalMargin.set(saved.criticalMargin??25);this.expenseCap.set(saved.expenseCap??65);this.autoReview.set(saved.autoReview??true)}}catch{/* Keep safe defaults when stored settings are invalid. */}}
 switchTab(tab:Tab){this.tab.set(tab);this.animate()} changeDays(v:number){this.days.set(v);this.animate()} animate(){this.pg.resetPage();this.refreshing.set(false);requestAnimationFrame(()=>this.refreshing.set(true));setTimeout(()=>this.refreshing.set(false),480)}
 openProfitSettings(){this.settingsSaved.set(false);this.settingsOpen.set(true)}
 saveProfitSettings(){this.warningMargin.set(Math.min(this.warningMargin(),this.targetMargin()));this.criticalMargin.set(Math.min(this.criticalMargin(),this.warningMargin()));localStorage.setItem('mealmate-profit-settings',JSON.stringify({alertsEnabled:this.alertsEnabled(),targetMargin:this.targetMargin(),warningMargin:this.warningMargin(),criticalMargin:this.criticalMargin(),expenseCap:this.expenseCap(),autoReview:this.autoReview()}));this.settingsSaved.set(true);this.profitAlertDismissed.set(false);setTimeout(()=>this.settingsOpen.set(false),700)}
 resetProfitSettings(){this.alertsEnabled.set(true);this.targetMargin.set(35);this.warningMargin.set(32);this.criticalMargin.set(25);this.expenseCap.set(65);this.autoReview.set(true)}
 name(x:Detail){return this.locale.isRtl()?x.ar:x.en} category(key:string){const x=DETAILS.find(d=>d.key===key);return x?this.name(x):key} change(x:Detail){return(x.value-x.previous)/x.previous*100} onPageChange(p:number){this.pg.onPageChange(p,this.totalPages())}
 export(){const t=this.t();const rows=[[t.ref,t.statement,t.category,t.amount,t.direction,t.date],...this.moves().map(x=>[x[0],this.locale.isRtl()?x[2]:x[3],this.category(x[1]),x[4],x[5]==='in'?t.incoming:t.outgoing,x[6]])];const csv='\uFEFF'+rows.map(r=>r.map(v=>`"${v}"`).join(',')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='platform-financial-report.csv';a.click();URL.revokeObjectURL(u)}
}
