import { Component, computed, inject, signal } from '@angular/core';
import { DecimalPipe, NgClass } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideArrowDownLeft, lucideArrowUpRight, lucideBanknote, lucideCheck, lucideClock3, lucideCreditCard, lucideDownload, lucideEye, lucideLandmark, lucideLockKeyhole, lucidePlus, lucideRotateCcw, lucideSearch, lucideShieldCheck, lucideWalletCards, lucideX } from '@ng-icons/lucide';
import { AppLocaleService } from '@/core/i18n/app-locale.service';
import { MmTablePaginationComponent } from '@/shared/components/layout/table-pagination';
import { createTablePagination } from '@/shared/utils/table-pagination.util';

type Tab='wallets'|'adjustments'|'transfers'; type Status='posted'|'pending'|'processing'|'rejected'; type Kind='credit'|'debit'|'transfer';
type Row={id:string;customerAr:string;customerEn:string;kind:Kind;categoryAr:string;categoryEn:string;amount:number;balance:number;status:Status;date:string;reference:string;reasonAr:string;reasonEn:string;bank?:string;dueDays?:number};
const ROWS:Row[]=[
 {id:'WLT-9201',customerAr:'أحمد السالم',customerEn:'Ahmed Al-Salem',kind:'credit',categoryAr:'تعويض شكوى جودة',categoryEn:'Quality complaint compensation',amount:8.5,balance:34.75,status:'posted',date:'2026-07-01 10:30',reference:'C-482',reasonAr:'تعويض قيمة وجبة غير مطابقة وخصمها من مستحق المطعم.',reasonEn:'Compensation for incorrect meal, deducted from restaurant payout.'},
 {id:'WLT-9200',customerAr:'سارة محمد',customerEn:'Sara Mohamed',kind:'credit',categoryAr:'استرداد إلغاء جزئي',categoryEn:'Partial cancellation refund',amount:24,balance:41.2,status:'posted',date:'2026-07-01 09:10',reference:'CAN-614',reasonAr:'صافي الاسترداد بعد خصم الأيام التشغيلية.',reasonEn:'Net refund after operational day deduction.'},
 {id:'TRF-1842',customerAr:'خالد علي',customerEn:'Khaled Ali',kind:'transfer',categoryAr:'تحويل إلى حساب بنكي',categoryEn:'Bank account transfer',amount:58.75,balance:0,status:'processing',date:'2026-06-30 15:45',reference:'BNK-7731',reasonAr:'طلب تحويل رصيد المحفظة إلى الحساب البنكي المسجل.',reasonEn:'Wallet balance transfer to registered bank account.',bank:'NBK ••4921',dueDays:16},
 {id:'WLT-9197',customerAr:'منى إبراهيم',customerEn:'Mona Ibrahim',kind:'debit',categoryAr:'استخدام رصيد للاشتراك',categoryEn:'Balance used for subscription',amount:18,balance:6.5,status:'posted',date:'2026-06-30 12:20',reference:'SUB-10582',reasonAr:'استخدام الرصيد في تجديد الاشتراك الشهري.',reasonEn:'Balance used for monthly subscription renewal.'},
 {id:'TRF-1839',customerAr:'يوسف حسن',customerEn:'Youssef Hassan',kind:'transfer',categoryAr:'تحويل إلى حساب بنكي',categoryEn:'Bank account transfer',amount:72,balance:4.1,status:'pending',date:'2026-06-29 17:05',reference:'BNK-7698',reasonAr:'بانتظار مراجعة بيانات الحساب البنكي.',reasonEn:'Awaiting bank account details review.',bank:'KFH ••1184',dueDays:18},
 {id:'WLT-9191',customerAr:'فاطمة عادل',customerEn:'Fatma Adel',kind:'credit',categoryAr:'تعويض تأخير توصيل',categoryEn:'Delivery delay compensation',amount:4.5,balance:19.8,status:'posted',date:'2026-06-29 11:35',reference:'C-479',reasonAr:'تعويض تلقائي عن تجاوز وقت التوصيل.',reasonEn:'Automatic compensation for delivery SLA breach.'},
 {id:'WLT-9188',customerAr:'عمر سامي',customerEn:'Omar Samy',kind:'credit',categoryAr:'تعديل يدوي للرصيد',categoryEn:'Manual balance adjustment',amount:10,balance:27,status:'pending',date:'2026-06-28 14:10',reference:'ADJ-332',reasonAr:'تعديل مقدم من الدعم يحتاج اعتمادًا ماليًا.',reasonEn:'Support adjustment requiring finance approval.'},
 {id:'TRF-1831',customerAr:'نورة خالد',customerEn:'Noura Khaled',kind:'transfer',categoryAr:'تحويل إلى حساب بنكي',categoryEn:'Bank account transfer',amount:96.25,balance:2,status:'rejected',date:'2026-06-27 10:00',reference:'BNK-7612',reasonAr:'رقم IBAN غير مطابق لاسم صاحب الحساب.',reasonEn:'IBAN does not match the account holder name.',bank:'Boubyan ••9012',dueDays:19},
 {id:'WLT-9180',customerAr:'عبدالله ناصر',customerEn:'Abdullah Nasser',kind:'debit',categoryAr:'استخدام رصيد للترقية',categoryEn:'Balance used for upgrade',amount:31,balance:0,status:'posted',date:'2026-06-26 18:25',reference:'SUB-10490',reasonAr:'ترقية الباقة باستخدام الرصيد المتاح.',reasonEn:'Plan upgrade using available wallet balance.'},
];

@Component({selector:'mm-wallet-support-page',standalone:true,imports:[DecimalPipe,NgClass,FormsModule,NgIcon,MmTablePaginationComponent],providers:[provideIcons({lucideArrowDownLeft,lucideArrowUpRight,lucideBanknote,lucideCheck,lucideClock3,lucideCreditCard,lucideDownload,lucideEye,lucideLandmark,lucideLockKeyhole,lucidePlus,lucideRotateCcw,lucideSearch,lucideShieldCheck,lucideWalletCards,lucideX})],templateUrl:'./wallet-support-page.component.html',styleUrl:'./wallet-support-page.component.scss',host:{class:'block'}})
export class WalletSupportPageComponent{
 readonly locale=inject(AppLocaleService);readonly tab=signal<Tab>('wallets');readonly status=signal<'all'|Status>('all');readonly search=signal('');readonly selected=signal<Row|null>(null);readonly rows=signal<Row[]>(ROWS);readonly toast=signal('');readonly refreshing=signal(false);readonly adjustmentOpen=signal(false);readonly adjustmentCustomer=signal('');readonly adjustmentKind=signal<'credit'|'debit'>('credit');readonly adjustmentAmount=signal(0);readonly adjustmentReason=signal('');readonly frozenCustomers=signal<Set<string>>(new Set());readonly pg=createTablePagination(6);readonly currentPage=this.pg.currentPage;readonly pageSize=this.pg.pageSize;
 readonly t=computed(()=>this.locale.isRtl()?{wallets:'حركات المحفظة',adjustments:'تعديلات الرصيد',transfers:'التحويلات البنكية',totalBalances:'إجمالي الأرصدة',credits:'إضافات هذا الشهر',pending:'بانتظار الاعتماد',transferred:'تحويلات مكتملة',all:'كل الحالات',posted:'مكتملة',pendingStatus:'معلّقة',processing:'قيد التحويل',rejected:'مرفوضة',export:'تصدير',search:'ابحث بالعميل أو المرجع أو رقم العملية...',ledger:'سجل المحفظة والدعم المالي',ledgerSub:'متابعة الاستردادات والتعويضات والتعديلات والتحويلات',operation:'العملية',customer:'العميل',category:'نوع الحركة',amount:'المبلغ',balance:'الرصيد بعد الحركة',status:'الحالة',date:'التاريخ',action:'إجراء',details:'التفاصيل',items:'حركة',noData:'لا توجد عمليات مطابقة',credit:'إضافة',debit:'خصم',transfer:'تحويل بنكي',currency:'د.ك',reason:'سبب الحركة',reference:'المرجع المرتبط',bank:'الحساب البنكي',deadline:'مهلة التحويل',days:'يوم عمل متبقي',approve:'اعتماد العملية',complete:'تأكيد التحويل',reject:'رفض',close:'إغلاق',done:'تم تحديث العملية بنجاح',rule:'يجب تنفيذ التحويلات البنكية خلال 21 يوم عمل من تاريخ الطلب'}:{wallets:'Wallet activity',adjustments:'Balance adjustments',transfers:'Bank transfers',totalBalances:'Total balances',credits:'Credits this month',pending:'Awaiting approval',transferred:'Completed transfers',all:'All statuses',posted:'Completed',pendingStatus:'Pending',processing:'Processing',rejected:'Rejected',export:'Export',search:'Search customer, reference, or transaction...',ledger:'Wallet & financial support ledger',ledgerSub:'Track refunds, compensation, adjustments, and transfers',operation:'Transaction',customer:'Customer',category:'Category',amount:'Amount',balance:'Balance after',status:'Status',date:'Date',action:'Action',details:'Details',items:'transactions',noData:'No matching transactions',credit:'Credit',debit:'Debit',transfer:'Bank transfer',currency:'KD',reason:'Transaction reason',reference:'Linked reference',bank:'Bank account',deadline:'Transfer deadline',days:'business days left',approve:'Approve transaction',complete:'Confirm transfer',reject:'Reject',close:'Close',done:'Transaction updated successfully',rule:'Bank transfers must complete within 21 business days of request'});
 readonly filtered=computed(()=>{const q=this.search().toLowerCase().trim();return this.rows().filter(x=>(this.tab()==='wallets'||(this.tab()==='adjustments'&&x.kind!=='transfer')||(this.tab()==='transfers'&&x.kind==='transfer'))&&(this.status()==='all'||x.status===this.status())&&(!q||x.id.toLowerCase().includes(q)||x.customerAr.toLowerCase().includes(q)||x.customerEn.toLowerCase().includes(q)||x.reference.toLowerCase().includes(q)))});readonly paginated=this.pg.paginated(this.filtered);readonly totalPages=this.pg.totalPages(this.filtered);
 readonly stats=computed(()=>({balances:this.rows().reduce((s,x)=>s+x.balance,0),credits:this.rows().filter(x=>x.kind==='credit').reduce((s,x)=>s+x.amount,0),pending:this.rows().filter(x=>x.status==='pending'||x.status==='processing').reduce((s,x)=>s+x.amount,0),transferred:this.rows().filter(x=>x.kind==='transfer'&&x.status==='posted').reduce((s,x)=>s+x.amount,0)}));
 name(x:Row){return this.locale.isRtl()?x.customerAr:x.customerEn} category(x:Row){return this.locale.isRtl()?x.categoryAr:x.categoryEn} reason(x:Row){return this.locale.isRtl()?x.reasonAr:x.reasonEn} kindLabel(k:Kind){return k==='credit'?this.t().credit:k==='debit'?this.t().debit:this.t().transfer} statusLabel(s:Status){return s==='posted'?this.t().posted:s==='pending'?this.t().pendingStatus:s==='processing'?this.t().processing:this.t().rejected} statusTone(s:Status){return s==='posted'?'bg-emerald-50 text-emerald-700':s==='pending'?'bg-amber-50 text-amber-700':s==='processing'?'bg-sky-50 text-sky-700':'bg-rose-50 text-rose-700'}
 switchTab(x:Tab){this.tab.set(x);this.animate()} animate(){this.pg.resetPage();this.refreshing.set(false);requestAnimationFrame(()=>this.refreshing.set(true));setTimeout(()=>this.refreshing.set(false),430)} update(x:Row,s:Status){this.rows.update(rows=>rows.map(r=>r.id===x.id?{...r,status:s}:r));this.selected.set(null);this.toast.set(this.t().done);setTimeout(()=>this.toast.set(''),2200)} onPageChange(p:number){this.pg.onPageChange(p,this.totalPages())}
 reverse(x:Row){this.rows.update(rows=>rows.map(r=>r.id===x.id?{...r,status:'rejected' as Status,reasonAr:`عكس العملية: ${r.reasonAr}`,reasonEn:`Reversed: ${r.reasonEn}`}:r));this.selected.set(null);this.notify(this.locale.isRtl()?'تم عكس العملية وتسجيلها':'Transaction reversed and logged')}
 reopen(x:Row){this.update(x,'pending')}
 toggleFreeze(customer:string){this.frozenCustomers.update(current=>{const next=new Set(current);next.has(customer)?next.delete(customer):next.add(customer);return next});this.notify(this.locale.isRtl()?'تم تحديث حالة المحفظة':'Wallet status updated')}
 createAdjustment(){const customer=this.adjustmentCustomer().trim(),amount=this.adjustmentAmount();if(!customer||amount<=0||!this.adjustmentReason().trim())return;const current=this.rows().find(x=>this.name(x)===customer);const row:Row={id:`ADJ-${Date.now().toString().slice(-5)}`,customerAr:customer,customerEn:customer,kind:this.adjustmentKind(),categoryAr:'تعديل يدوي للرصيد',categoryEn:'Manual balance adjustment',amount,balance:Math.max(0,(current?.balance??0)+(this.adjustmentKind()==='credit'?amount:-amount)),status:'pending',date:new Date().toISOString().slice(0,16).replace('T',' '),reference:`ADM-${Date.now().toString().slice(-4)}`,reasonAr:this.adjustmentReason(),reasonEn:this.adjustmentReason()};this.rows.update(rows=>[row,...rows]);this.adjustmentOpen.set(false);this.adjustmentAmount.set(0);this.adjustmentReason.set('');this.notify(this.locale.isRtl()?'تم إنشاء تعديل وبانتظار الاعتماد':'Adjustment created and pending approval')}
 notify(message:string){this.toast.set(message);setTimeout(()=>this.toast.set(''),2200)}
 export(){const t=this.t();const data=[[t.operation,t.customer,t.category,t.amount,t.balance,t.status,t.date],...this.filtered().map(x=>[x.id,this.name(x),this.category(x),x.amount,x.balance,this.statusLabel(x.status),x.date])];const csv='\uFEFF'+data.map(r=>r.map(v=>`"${v}"`).join(',')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='wallet-support.csv';a.click();URL.revokeObjectURL(u)}
}
